### ISSUE TITLE
Удаление из канала запросов, результаты в виде карточки

### ISSUE THREAD

**Issue by dmitrsosnin** [kreicer/dice-roller-bot#5]
Научить бота удалять сообщения пользователей из определённого канала, который назначен боту, и вместо обычного ответа публиковать примерно такую карточку: https://i.imgur.com/VbzckcC.png. Виден ник бросившего, виден результат броска, возможно, видны какие-то кнопки управления ("скопировать результат", например).

**Comment by kreicer** [comment]
Made a task for it.

**Comment by kreicer** [comment]
It will be part of a separate role-playing module.
