### ISSUE TITLE
Подмена ника пользователя именем персонажа

### ISSUE THREAD

**Issue by dmitrsosnin** [kreicer/dice-roller-bot#7]
Пользователь бросил кубик, бот с результатами броска вывел "подменный ник": если идёт игра, мастеру часто удобнее видеть имя персонажа, а не пилота. Автоматически и/или через запрос подменного броска ?roll_as, типа того.

**Comment by kreicer** [comment]
Converted to the task.

**Comment by kreicer** [comment]
It will be part of a separate role-playing module.
